#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\HomeController::index

accueil:
    path: /
    controller: App\Controller\HomeController::accueil
