#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /index
    controller: App\Controller\HomeController::index

accueil:
    path: /accueil
    controller: App\Controller\HomeController::accueil

apropos:
    path: /apropos
    controller: App\Controller\HomeController::apropos


contacter:
    path: /contacter
    controller: App\Controller\HomeController::contacter



